#! /usr/bin/env python3
"""
Read stdin, turn input into 8 bit binary, output binary to stdout
"""

import sys

def main(argv):
    # Reading stdin and encoding in bytes
    bytes_ = sys.stdin.read().encode()
    # format each byte as a length 8 binary number
    binary = [ f"{byte:08b}" for byte in bytes_ ]
    # output the binary
    sys.stdout.write("".join(binary)) 
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))
