#! /usr/bin/env python3

from sys import stdin,stdout
from argparse import ArgumentParser

def get_arguments():
    parser = ArgumentParser(description="Turn dos line endings into unix line endings.")
    return parser.parse_args()

def main(args):
    stdout.writelines(line.replace("\n","\r\n") for line in stdin.readlines)

if __name__ == '__main__':
    main(get_arguments())

