#!/usr/bin/env python3
import sys, argparse

# Get argument
argparser = argparse.ArgumentParser(description="Expand CSV data into columns.")
argparser.add_argument("-w","--width",help="Width of columns",type=int,default=15) 
argparser.add_argument("-f","--file",help="Input file",type=str)
args = argparser.parse_args()

instr = ""
if args.file is not None:
  with open(args.file) as handle:
    instr = handle.read()
else:
  instr = sys.stdin.read()


# Read input
# expand elements on line with width
for line in instr.split("\n"):
  outstr = ""
  for elem in line.split(","):
    # FEELSGOODMAN
    outstr += "{{:<{}}}".format(args.width).format(elem)
  # output
  print(outstr)
