#!/usr/bin/env python3
from sys import stdin
from argparse import ArgumentParser, FileType

# Get argument
def get_arguments():
    parser = ArgumentParser(description="Expand CSV data into columns.")
    parser.add_argument("-w","--width",help="Width of columns",
                            type=int,default=15) 
    parser.add_argument("-f","--file",help="Input file",type=FileType('r'))
    parser.add_argument("-c","--column-separator", dest="column",
                            help="Column separator", default=",")
    parser.add_argument("-l","--line-separator", dest="line",
                            help="Line separator", default="\n")
    return parser.parse_args()

def get_input(source):
    return source.read() if source is not None else stdin.read()

def main(args):
    input_ = get_input(args.file)
    # Read input
    # expand elements on line with width
    for line in input_.split(args.line):
        outstr = ""
        for elem in line.split(args.column):
            # Format string a format string, bro
            outstr += "{{:<{}}}".format(args.width).format(elem)
        # output
        print(outstr)

if __name__ == "__main__":
    main(get_arguments())
