#! /usr/bin/env python3

import sys
import click
import signal
import uuid


@click.command()
@click.option(
    "-n",
    "--number",
    type=int,
    help="The number of UUIDs to generate",
    default=1,
    show_default=True,
)
def generate_uuid(number: int):
    """
    Generate some number of UUIDs
    """
    for _ in range(number):
        print(str(uuid.uuid4()))


if __name__ == "__main__":
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    generate_uuid()
    sys.exit(0)
