#! /usr/bin/env python3

from argparse import ArgumentParser

def get_arguments():
    parser = ArgumentParser(description="List out the users on the current machine")
    parser.add_argument("-f","--file",default="/etc/passwd",
                        help="The user file to read (default: /etc/passwd)")
    return parser.parse_args()

def get_users(file_):
    with open(file_,'r') as handle:
        lines = handle.readlines()
    return (line.split(":")[0] for line in lines)

def main(args):
    users = get_users(args.file)
    print(*users,sep="\n")

if __name__ == '__main__':
    main(get_arguments())
