#! /usr/bin/env python3

import os, argparse 
from itertools import islice

def get_arguments():
    parser = argparse.ArgumentParser(description="Mark some number of directories in a given directory with a given mark.")
    parser.add_argument("--mark",help="Mark to put on directories.",required=True)
    parser.add_argument("-n","--number",help="The number of directories to mark. Default is half the directories.",type=int)
    parser.add_argument("--directory",help="The directory to work from.",default=os.getcwd())
    return parser.parse_args()

def get_child_directories(parent):
    result = os.listdir(args.directory)
    result = map(lambda x: os.path.join(args.directory,x), result)
    result = filter(lambda x: os.path.isdir(x), result)
    return sorted(result) 

def take(amount,iterable):
    return islice(iterable,amount)

if __name__ == "__main__":
    args = get_arguments()
    directories = get_child_directories(args.directory)
    num = len(directories)//2 if args.number is None else args.number
    for directory in islice(directories,num):
        new_directory = "{}{}".format(directory,args.mark)
        os.rename(directory,new_directory)
        print("{} -> {}".format(directory,new_directory))
