#! /usr/bin/env python3

import os, argparse 

def get_arguments():
    parser = argparse.ArgumentParser(description="Mark a list of directories with the given mark.")
    parser.add_argument("--mark",help="Mark to put on directories.",required=True)
    parser.add_argument("--directories","-d",nargs="+",help="List of directories to mark")
    return parser.parse_args()

if __name__ == "__main__":
    args = get_arguments()
    for directory in filter(os.path.isdir,args.directories):
        new_directory = "{}{}".format(directory,args.mark)
        os.rename(directory,new_directory)
        print("{} -> {}".format(directory,new_directory))
