#! /usr/bin/env python3

import argparse, os

def get_arguments():
    parser = argparse.ArgumentParser(description="Expand appname identifier into the application name")
    parser.add_argument("-d","--directory",help="The directory to work in. Current working directory by default",default=os.getcwd())
    parser.add_argument("-i","--identifier",help="The identifier to substitute.",required=True)
    parser.add_argument("-s","--substitute",help="The value to replace the identifier with.",required=True)
    return parser.parse_args()

if __name__ == "__main__":
    args = get_arguments()
    paths = os.listdir(args.directory)
    for path in paths: 
        new_path = path.replace(args.identifier,args.substitute)
        os.replace(os.path.join(args.directory, path), os.path.join(args.directory, new_path))

