#! /usr/bin/env python3

import argparse,sys

def get_arguments():
    parser = argparse.ArgumentParser(description="Take text through stdin and print sarcastified text to stdout.")
    return parser.parse_args()

def sarcastify(text):
    new_text = ""
    for index,char in zip(range(len(text)),text):
        if index % 2 == 0:
            new_text += char.lower()
        else:
            new_text += char.upper()
    return new_text

if __name__ == "__main__":
    args = get_arguments()
    text = sys.stdin.read().rstrip()
    print(sarcastify(text))

