#! /usr/bin/env python3

from sys import stdin
from argparse import ArgumentParser

def get_arguments():
    parser = ArgumentParser(description="Take text, sarcastify it, and output it to stdout.")
    text_group = parser.add_mutually_exclusive_group(required=True)
    text_group.add_argument("-t","--text",help="Specified text to sarcastify")
    text_group.add_argument("--stdin",help="Text should be read from stdin",action="store_true")
    return parser.parse_args()

def sarcastify(text):
    new_text = ""
    for index,char in enumerate(text):
        if index % 2 == 0:
            new_text += char.lower()
        else:
            new_text += char.upper()
    return new_text

def main(args):
    text = args.text if not args.stdin else stdin.read().rstrip()
    print(sarcastify(text))

if __name__ == "__main__":
    main(get_arguments())

