#! /usr/bin/env python3

import re
import json
import urllib.request
import urllib.parse
import os
import getpass
import tempfile
import subprocess
from pprint import pprint

CONFIG = {
        "PARAMS" : [
            ("api_user", "webservices"),
            ("api_pass", "Sparty1855"),
            ("api_action", "ticket_list"),
            ("api_output", "json"),
            ],
        "URL" : "https://www.egr.msu.edu/decs/helpdesk/admin/api.php",
        "SHARE" : "/media/reinstallbackups",
        "DOMAIN" : "egr",
        }

def make_dict_get_params(params):
    result = "?"
    for key,value in params:
        result += "{}={}&".format(urllib.parse.quote(key),urllib.parse.quote(value))
    return result.rstrip("&")

def mount_share(share,domain):
    temp_dir = tempfile.mkdtemp()
    username = input("Domain Account Username: ")
    password = getpass.getpass("Domain Account Password: ")
    options = "vers=3.0,domain={},username={},password={}".format(
            domain,username,password) 
    #prefix = domain + "\\"
    #if not username.startswith(prefix):
    #    username = prefix + username
    cmd = ["mount","-t", "cifs", share, temp_dir,"-o",options]
    subprocess.run(cmd)
    return temp_dir 

def unmount_share(mount_point):
    cmd = ["umount", mount_point]
    subprocess.run(cmd)

def directories_to_tickets(directories):
    tickets = set()
    ticket_expr = re.compile("^[0-9]+")
    for directory in directories:
        match = ticket_expr.match(directory)
        if match is not None:
            tickets.add(match.group())
    assert len(tickets) > 0, "There are no ticket directories in filer!"
    avg_length = (sum ([ len(ticket) for ticket in tickets ])) / len(tickets)
    tickets = {ticket for ticket in tickets
                if (len(ticket) > (avg_length/2) and 
                    len(ticket) < (avg_length*2)
                    ) 
                }
    return tickets

if __name__ == '__main__':
    query_url = (CONFIG["URL"] + make_dict_get_params(CONFIG["PARAMS"]))
    domain = CONFIG["DOMAIN"]
    share = CONFIG["SHARE"]
    tickets = set()
    #mount_point = None
    assert os.path.exists(share), "Path '{}' does not exist!".format(share)
    try:
        #mount_point = mount_share(share,domain)
        directories = os.listdir(share)
        tickets = directories_to_tickets(directories)
        query_url += "&ids=" + urllib.parse.quote(",".join(tickets))
    except:
        print("Something horrible has happened!")
    raw_json = ""
    with urllib.request.urlopen(query_url) as handle:
        raw_json = handle.read().decode('utf-8')
    obj_json = json.loads(raw_json)
    print("id,time,status")
    for key,ticket in obj_json.items():
        if key.isdigit():
            time = ticket["a_duration"]
            id_ = ticket["id"]
            status = ticket["a_statustitle"]
            print("{},{},{}".format(id_, time, status))
