#!/bin/sh
#Author: Sean Joseph
#Version: 1.0.1
#This script will do the few steps it takes to create 
#an executable file with a shebang for whatever interpreter I give it.

usage_string="
Usage gen-script -f <filename> -i <interpreter> [-a <author>] [-v <version>] [-y] [-h]
	-f : Specify file to generate
	-i : Specify interpreter
	-a : Specify author [optional]
	-v : Specify version [optional]
	-y : Specify force if file already exists [optional]
	-h : Print out this message and exit [optional]
"

# <arguments>
target_file=
interpreter=
author=$USER
version="0.0.1"
force=false
# </arguments>

# <functions>
print_usage ( )
{
	echo "$usage_string" >&2
}

print_usage_and_rip ( )
{
	print_usage
	exit 0
}

print_prompt ( )
{
	echo "$@" >&2
}

print_error ( )
{
	echo "Error: $@" >&2
}

print_error_and_die ( )
{
	print_error $@
	print_usage
	exit 1
}
# </functions>

# <argument_processing>
while getopts :f:F:i:I:a:A:v:V:hHyY opts
do
	case $opts in
		f | F)
			target_file=$OPTARG
			;;
		i | I)
			interpreter=$OPTARG
			;;
		a | A)
			author=$OPTARG
			;;
		v | V)
			version=$OPTARG
			;;
		h | H)
			print_usage_and_rip
			;;
		y | Y)
			force=true
			;;
		'?')
			print_error_and_die "bad argument found"
			;;
	esac
done
# </argument_processing>

# <argument_validation>
if ! [ -f $interpreter ] || ! [ -x $interpreter ]
then
	print_error_and_die "interpreter provided is not usable"
fi

if ! [ "$target_file" ]
then
	print_error_and_die "no target file specified"
elif [ -e $target_file ] && ! $force 
then
	print_prompt "$target_file already exists. Overwrite?(y/n) \c"
	read answer
	if [ "x$answer" != "xy" ] && [ "x$answer" != "xY" ]
	then
		print_error_and_die "file already exists"
	fi
fi
# </argument_validation>

# <debug>
# <off/> echo "Target File: $target_file"
# <off/> echo "Interpreter: $interpreter"
# <off/> echo "Author: $author"
# <off/> echo "Version: $version"
# <off/> echo "Force: $force"
# <off/> exit 0
# </debug>

# <body>
cat <<EOFILE > "$target_file"
#!$interpreter
###############################################################
#Author: $author
#Version: $version
#Description:
#
###############################################################
#usage_string="Usage: <command/> <command_args/> [-h]
#	-h : Print out this message and then exit [optional]"

# <imports>
# </imports>

# <arguments>
# </arguments>

# <functions>
# </functions>

# <argument_processing>
# </argument_processing>

# <argument_validation>
# </argument_validation>

# <body>
# </body>
EOFILE

chmod +x "$target_file"
# </body>
