#!/bin/sh
###############################################################
# Author: Sean Joseph
# Version: 0.0.1
# Description:
#
###############################################################
#name="functions"
#version="0.0.1"
#author="Sean Joseph"
#usage_string="Usage: $name <command_args/> [-h]
#	-h : Print out this message and then exit [optional]"

# <imports>
# </imports>

# <arguments>
# </arguments>

# <functions>
equal ( ) {
	case "$1" in
		"$2")
			return 0
			;;
	esac	
	return 1
}
#print_usage ( )
#{
#	echo "$usage_string" >&2
#}
#
#print_error ( )
#{
#	echo "Error: $@" >&2
#}
#
#print_error_and_die ( )
#{
#	print_error $@
#	print_usage
#	exit 1
#}
#
#print_usage_and_die ( )
#{
#	print_usage
#	exit 0
#}
#
#
# </functions>

# <argument_processing>
#while getopts :hH opts
#do
#	case $opts in
#		 h | H)
#			print_usage_and_die
#			;;
#		'?')
#			print_error_and_die "Bad argument!"
#			;;
#	esac
#done
#shift $((OPTIND - 1))
# </argument_processing>

# <argument_validation>
# </argument_validation>

# <body>
if equal "wut" "wut"
then
	echo "Equal!"
else
	echo "Not Equal!"
fi
# </body>
