#!/bin/sh
# Count the frequency of words and display n(Default 25)
# most frequently used words.
#
# Usage: wf [n]

tr -cs A-Za-z\' '\n' | #Special characters are now newlines
tr A-Z a-z | #Uppercase letters to lower
grep -v '^[ \t\n]*$' | #Remove empty lines
sort | #sort output
uniq -c | #Remove duplicates and count
sort -k1,1nr -k2 | #Sort first by count in reverse then word
sed ${1:-25}q # Output some number of lines (or 25 if not specified)

