#!/bin/sh

#Make a lovely directory out of the passwd file!
umask 077 #Restrict temp file access

#Temp file names!
person="/tmp/pd.key.person.$$"
office="/tmp/pd.key.office.$$"
telephone="/tmp/pd.key.telephone.$$"
user="/tmp/pd.key.user.$$"

trap "exit 1" HUP INT PIPE QUIT TERM
#trap "rm -f $person $office $telephone $user" EXIT

awk -F: '{ print $1 ":" $5 }' > $user

sed -e 's=/.*= =' \
	-e 's=^\([^:]*\):\(.*\) \([^ ]*\)=\1:\3, \2=' < $user | sort > $person

cat $person

umask 755
