#!/bin/sh
#Author: Sean Joseph
#Version: 0.0.1
#This script will do the few steps it takes to create 
#an executable file with a shebang for whatever interpreter I give it.

# gen-script <filename> <interpreter>

# Features for next version:
# Check if file exists and ask before clobbering
# Check to see if interpreter exists on system

usagestring="Usage gen-script <filename> <interpreter>"

if ! [ -f $2 ] || ! [ -x $2 ]
then
	echo "Interpreter provided is not usable"
	echo "$usagestring"
	exit 1
fi

if [ -e $1 ]
then
	echo "$1 already exists. Overwrite?(y/n) \c"
	read answer
	if [ "x$answer" != "xy" ] && [ "x$answer" != "xY" ]
	then
		echo "File already exists"
		echo "$usagestring"
		exit 1
	fi
fi

cat <<EOFILE > $1 
#!$2
###############################################################
#Author:
#Version:
#Description:
#
#Usage:
###############################################################

EOFILE

chmod +x $1
