#!/bin/sh
###############################################################
# Author: Sean Joseph
# Version: 0.0.1
# Description:
#
###############################################################
#usage_string="Usage: <command/> <command_args/> [-h]
#	-h : Print out this message and then exit [optional]"

# <imports>
# </imports>

# <arguments>
# </arguments>

# <functions>
# </functions>

# <argument_processing>
# </argument_processing>

# <argument_validation>
# </argument_validation>

# <body>
printenv | sed -e 's/=.*//'
# </body>
