#!/bin/sh
###############################################################
#Author: Sean Joseph
#Version: 0.0.1
#Description:
# Create a new multiboot usb given a device handle
#Usage: new-bootdrive (-d|--dev) <device handle> (-h|--help)
#	(--uefi,-u,--bios,-b)
###############################################################
uefi=false
bios=false
device="nice try, satan."

if [ "x$UID" != "x0" ]
then
	echo "This script requires root permissions!"
	exit 1
fi
