#!/bin/sh
###############################################################
# Author: Sean Joseph
# Version: 1.0.0
# Description:
#
###############################################################
name="tunnel-trainman"
version="1.0.0"
author="Sean Joseph"
usage_string="Usage: $name [-h]
	-h : Print out this message and then exit [optional]"

# <imports>
# </imports>

# <arguments>
# </arguments>

# <functions>

print_usage ( )
{
	echo "$usage_string" >&2
}

print_error ( )
{
	echo "Error: $@" >&2
}

print_error_and_die ( )
{
	print_error $@
	print_usage
	exit 1
}

print_usage_and_die ( )
{
	print_usage
	exit 0
}


# </functions>

# <argument_processing>
while getopts :hH opts
do
	case $opts in
		 h | H)
			print_usage_and_die
			;;
		'?')
			print_error_and_die "Bad argument!"
			;;
	esac
done
shift $((OPTIND - 1))
# </argument_processing>

# <argument_validation>
# </argument_validation>

# <body>
tunnel-connection -c mandark -d egr.msu.edu -u joseph62 -t trainman -r 5432 -l 5843
# </body>
