#!/bin/sh
###############################################################
# Author: Sean Joseph
# Version: 0.0.1
# Description:
# Get the usage line for the given license
###############################################################
usage_string="Usage: lic-line -l <license name> [-h]
	-l : The license string to look for
	-h : Print out this message and then exit [optional]"

# <arguments>
license=
# </arguments>

# <functions>
print_usage ( )
{
	echo "$usage_string" >&2
}

print_usage_and_rip ( )
{
	print_usage
	exit 0
}

print_prompt ( )
{
	echo "$@" >&2
}

print_error ( )
{
	echo "Error: $@" >&2
}

print_error_and_die ( )
{
	print_error $@
	print_usage
	exit 1
}
# </functions>

# <argument_processing>
while getopts :l:L:hH opts
do
	case $opts in
		l | L)
			license=$OPTARG
			;;
		h | H)
			print_usage_and_rip
			;;
		'?')
			print_error_and_die "Bad argument!"
			;;
	esac
done
# </argument_processing>

# <argument_validation>
if [ -z "$license" ]
then
	print_error_and_die "License not specified!"
fi
# </argument_validation>

# <body>
lmutil lmstat -c 22126@lms1 -a | grep -E "Users of $license:"
# </body>
